apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-php-deployment
spec:
  selector:
    matchLabels:
      app: kube-php
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kube-php
    spec:
      containers:
      - name: kube-php
        image: dylanops/kube-php:8.3.1
        ports:
        - containerPort: 80