version: '3'

services:

  app:
    image: kube-php:8.3
    restart: always
    container_name: app
    # volumes:
      # - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    environment:
      PHP_IDE_CONFIG: 'serverName=web'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80

  # mysql:
  #   image: mysql:8.0.16
  #   container_name: mysql
  #   volumes:
  #     - ./conf/mysql/my.conf:/etc/mysql/my.cnf
  #     - ./data/backup:/var/backup
  #     - ./data/mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app

  # elasticsearch:
  #   image: elasticsearch:7.16.3
  #   container_name: elasticsearch
  #   volumes:
  #     - ./data/es-data:/usr/share/elasticsearch/data
  #     - ./data/es-plugins:/usr/share/elasticsearch/plugins
  #   ports:
  #     - "9300:9300"
  #     - "9200:9200"
  #   environment:
  #     discovery.type: single-node
  #   networks:
  #     - app

  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/usr/local/redis/data
  #   command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
  #   networks:
  #     - app

networks:
  app:
    driver: bridge